spring.application.name=HotSpotter
spring.config.import=optional:file:src/main/resources/.env.properties


# ===== Server configuration =====
server.servlet.context-path=/api
server.forward-headers-strategy=native
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173/}


# ===== MongoDB database connection variables =====
spring.data.mongodb.database=${MONGODB_DATABASE:hotspotter}
spring.data.mongodb.uri=${MONGODB_URI}


# ===== Repository management configuration =====
repositories.base-directory=${PROJECT_BASE_DIRECTORY:/tmp/hotspotter}
repositories.min-free-space-gb=${REPOSITORIES_MIN_FREE_SPACE_GB:10}
repositories.cleanup-strategy=${REPOSITORIES_CLEANUP_STRATEGY:LEAST_RECENTLY_USED}
repositories.clone-monitoring-interval-percentage=${CLONE_MONITORING_INTERVAL_PERCENTAGE:20}
repositories.update-monitoring-interval-percentage=${UPDATE_MONITORING_INTERVAL_PERCENTAGE:50}


# ===== File analysis configuration =====
file-analysis.base-directory=${PROJECT_BASE_DIRECTORY:/tmp/hotspotter}


# ===== Logging configuration =====
logging.level.pwr.zpi.hotspotter=${LOGGING_LEVEL:INFO}
logging.level.org.springframework.data.mongodb=INFO


# ===== Authentication configuration =====
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${HOST_BASE_URL:http://localhost:8080/api}/login/oauth2/code/{registrationId}
google.redirect-uri=${LOGIN_REDIRECT_URL:http://localhost:8080/login/success}


# openssl rand -base64 128
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

cookie.secure=${COOKIE_SECURE:false}
cookie.domain=${COOKIE_DOMAIN:localhost}
cookie.same-site=${COOKIE_SAME_SITE:Lax}


# ===== Google Cloud configuration =====
google.project-id=${GOOGLE_PROJECT_ID}


# ===== SonarQube configuration =====
sonar.host-url=${SONAR_HOST_URL:http://localhost:9000}
sonar.scanner-path=${SONAR_SCANNER_PATH:sonar-scanner}
sonar.log-sonar-output=${SONAR_LOG_SONAR_OUTPUT:false}
